### ISSUE TITLE
استفسار

### ISSUE THREAD

**Issue by Tayeb-Ali** [x249/node-api#47]
اهاا المشروع دا لسه  شغال تطور فيو ولا كيف..؟
و خططك شنو .؟

**Comment by phr3nzy** [comment]
Basically, all that's left is adding more tests and documentation. I'm gonna deprecate the GraphQL feature since it's redundant technology-wise. If you have anything, just fire up a PR :)

**Comment by Tayeb-Ali** [comment]
F GraphQl . F facebook>

**Comment by phr3nzy** [comment]
I meant I am discarding GraphQL (not using it). It's a good technology senseless to implement in this project scope.

**Comment by Tayeb-Ali** [comment]
Sorry for that.
I think you want use GraphQl
