### ISSUE TITLE
add new feature

### ISSUE THREAD

**Issue by Tayeb-Ali** [x249/node-api#49]
I love CLI , I use CLI in Laravel & AdonicJs
I think is help full. Something like, Create Controller and Model, Add ORM like TypeOrm.

https://typeorm.io/#/
https://github.com/balderdashy/waterline
http://www.camintejs.com/
`
see https://github.com/DetaElectPro/MEAN
i am add Angular Cli.

**Comment by phr3nzy** [comment]
This is a really good feature idea. If you're going to work on it, please submit a draft for how it'll work, pros and cons etc. so I can work on integrating it in the documentation.

**Comment by Tayeb-Ali** [comment]
ok i will try. i already have Zool-Cli is work with ZooLCrud .
is hard to rewrite new one because of time.
and i am not real programer :)

**Comment by Tayeb-Ali** [comment]
Hi pro  Any Update  For me   👯 

قاعدة استخدم البتاع ده للان  , ههههههه
تعال اعمل تحديث
